FLASK_SECRET_KEY = 'namana'
DATABASE_URI = 'sqlite:///test.db'
DEBUG = True
SQLALCHEMY_TRACK_MODIFICATIONS = False

GOOGLE_CLIENT_ID = ''
GOOGLE_CLIENT_SECRET = ''

WUNDERLIST_CLIENT_ID = ''
WUNDERLIST_CLIENT_SECRET = ''
WUNDERLIST_NAME = 'Splitwise'

APPLICATION_ROOT = None

GOOGLE_ANALYTIC_ENABLED = False
GOOGLE_ANALYTIC_ID = ''

BEHIND_PROXY = False